### ISSUE TITLE
Breaking change in evcc 0.203.0

### ISSUE THREAD

**Issue by dlein** [TobiasNeuschulz/EVCC-Enphase#3]
In https://github.com/evcc-io/evcc/releases/tag/0.203.0 gibt es einen Breaking Change bzgl. der Authentifizierung in der custom-Konfiguration.

In https://github.com/TobiasNeuschulz/EVCC-Enphase/blob/main/Enphase-IQ-Battery.md#option-2-nutzung-evcc-custom-template-f%C3%BCr-die-enphase-iq-battery muss `password` durch `token` ersetzt werden, sonst gibt es ab evcc 0.203.0 einen `401` statt der Daten.

Also jeweils
```
    auth:
      type: bearer
      token: <Enter Enphase Token here>
    insecure: true
```
statt
```
    auth:
      type: bearer
      password: <Enter Enphase Token here>
    insecure: true
```
